# Generated by Django 5.1.3 on 2024-11-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevilFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Paramecia', 'Paramecia'), ('Zoan', 'Zoan'), ('Logia', 'Logia')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Descripción de los poderes que otorga la fruta')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('date_birth', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('crew', models.CharField(blank=True, max_length=200, null=True)),
                ('fruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='WikiPage.devilfruit')),
            ],
        ),
    ]
