# Generated by Django 5.1.3 on 2024-11-24 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Desconocido', max_length=200)),
                ('number', models.IntegerField()),
                ('roman_name', models.CharField(max_length=100)),
                ('total_prime', models.CharField(max_length=100)),
                ('is_yonko', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('roman_name', models.CharField(max_length=100)),
                ('technicalFile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('saga_number', models.CharField(max_length=100)),
                ('saga_chapitre', models.CharField(max_length=100)),
                ('saga_volume', models.CharField(max_length=100)),
                ('saga_episode', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='character',
            name='birthday',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='bounty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='job',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='size',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WikiPage.crew'),
        ),
        migrations.AlterField(
            model_name='character',
            name='fruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WikiPage.fruit'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('chapter', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='WikiPage.arc')),
                ('saga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='WikiPage.saga')),
            ],
        ),
        migrations.DeleteModel(
            name='DevilFruit',
        ),
    ]
