# Generated by Django 5.1.3 on 2024-12-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiPage', '0002_arc_crew_fruit_saga_remove_character_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='arcs/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chapters/'),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fruits/'),
        ),
        migrations.AddField(
            model_name='saga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sagas/'),
        ),
    ]
