# Generated by Django 5.1.3 on 2024-12-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiPage', '0003_arc_image_chapter_image_character_image_fruit_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arc',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='saga',
            name='image',
        ),
        migrations.AddField(
            model_name='arc',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saga',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
