# Generated by Django 5.2 on 2025-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiPage', '0008_alter_section_options_remove_section_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video')], default='text', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
    ]
