# Generated by Django 5.2 on 2025-04-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiPage', '0009_alter_section_options_remove_section_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='Sin título', max_length=255),
        ),
    ]
