# Generated by Django 5.2 on 2025-05-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiPage', '0010_alter_section_options_section_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='roman_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='total_prime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
